public enum TZXBlockType:int
{
    Header = 0x00,
    StandardSpeedDataBlock = 0x10,
    TurboSpeedDataBlock = 0x11,
    PureTone = 0x12,
    SequenceOfPulsesOfVariousLengths = 0x13,
    PureDataBlock = 0x14,
    DirectRecordingBlock = 0x15,
    CswRecordingBlock = 0x18,
    GeneralizedDataBlock = 0x19,
    PauseSilenceOrStopTheTapeCommand = 0x20,
    GroupStart = 0x21,
    GroupEnd = 0x22,
    JumpToBlock = 0x23,
    LoopStart = 0x24,
    LoopEnd = 0x25,
    CallSequence = 0x26,
    ReturnFromSequence = 0x27,
    SelectBlock = 0x28,
    StopTheTapeIfIn48kMode = 0x2a,
    SetSignalLevel = 0x2b,
    TextDescription = 0x30,
    MessageBlock = 0x31,
    ArchiveInfo = 0x32,
    HardwareType = 0x33,
    CustomInfoBlock = 0x35,
    GlueBlock = 0x5a,
    // Not Real Blocks
    TapeDataBlock = 0x99,
    EndOfFile = 0xFF,
}
